### ISSUE TITLE
Errors on Debian Sid

### ISSUE THREAD

**Issue by licaon-kter** [shashlik/shashlik-build#1]
64-bit, nVidia 361.28 in [GLVND mode](https://devtalk.nvidia.com/default/topic/915640/unix-graphics-announcements-and-news/multiple-glx-client-libraries-in-the-nvidia-linux-driver-installer-package/)
Installed the DEB and  `kde-baseapps-bin` for _kdialog_.

```
setting icon3 
error: device '(null)' not found
error: device offline
error: device offline
error: device offline
Exception in thread Thread-1:
Traceback (most recent call last):
File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
self.run()
File "/usr/lib/python3.5/threading.py", line 862, in run
self._target(*self._args, **self._kwargs)
File "/opt/shashlik/bin/shashlik-run", line 70, in send_icon
with open(icon_path, "rb") as icon:
FileNotFoundError: [Errno 2] No such file or directory: '/home/user/.local/share/shashlik//com.app.apk.png'
** Error: Unable to connect to activity manager; is the system running?
** Error: Unable to connect to activity manager; is the system running?
** Error: Unable to connect to activity manager; is the system running?
** No activities found to run, monkey aborted.
error: device '(null)' not found
```

Editing **/opt/shashlik/bin/shashlik-run** by changing
`shashlik_dir = os.path.expanduser("~/.local/share/shashlik/")` to
`shashlik_dir = os.path.expanduser("~/.local/share/shashlik")` does not help, the same error occurs (without the second `/`).

Message log is spammed with `kvm: vcpu0 disabled perfctr wrmsr: 0xc1 data 0xabcd`

Once it did `optimize apps`.
Once it did load/show an actual icon.
Most of the times it does show the navbar, with back/home/task buttons.

**Comment by davidedmundson** [comment]
Hopefully the icon issue is fixed in 0.9.1.

As for the above log; the app you were launching failed to install,  Try re-installing the apk and re-running now the icon problem is fixed.

**Comment by licaon-kter** [comment]
Icons fixed, by reinstalling.

**Comment by licaon-kter** [comment]
This really needs `-debug all` in emulator at this stage.

Anyway, here it stalls with this repeating message:

```
emulator: Error while connecting to socket '127.0.0.1:1970': 111 -> Connection refused
emulator: ASC 127.0.0.1:1970: Retrying connection. Connector FD = 35
emulator: Error while connecting to socket '127.0.0.1:1970': 111 -> Connection refused
emulator: ASC 127.0.0.1:1970: Retrying connection. Connector FD = 33
```

/LE: Post 10: https://code.google.com/p/android/issues/detail?id=174557#c10 got `bios.bin` and at least one ( com.aspyr.swkotor ) got beyond that error (it needs the Amazon store in my case, but I got the dialogue at least).

/LE: [Redir via telnet](https://stackoverflow.com/questions/26697270/ubuntu-all-android-emulatorx86-and-arm-stuck-on-error-while-connecting-to-so/27608428#27608428) not working either.

**Comment by davidedmundson** [comment]
Do you get the buttons at the bottom (the back and home buttons)

**Comment by licaon-kter** [comment]
Sometimes I get buttons.
Sometimes I get icon.
Sometimes I get dialogues (once for [SW:KoToR](http://www.amazon.com/Star-Wars-Knights-Old-Republic/dp/B00SNQGCNC/) and once for [Xash3D](https://github.com/SDLash3D/xash3d-android-project))

**Comment by CODeRUS** [comment]
similar log for me on ubuntu 14.04: https://gist.github.com/CODeRUS/027f9bc794c6b1a0bd38

**Comment by licaon-kter** [comment]
@CODeRUS Do use https://gist.github.com to post large logs, pls.

**Comment by CODeRUS** [comment]
sorry, updated post.

**Comment by ghost** [comment]
davidedmundson what kernel do you run? I am running 4.2.0-30-generic.

**Comment by licaon-kter** [comment]
0.9.3, still stuck at 

```
emulator: Error while connecting to socket '127.0.0.1:1970': 111 -> Connection refused
emulator: ASC 127.0.0.1:1970: Retrying connection. Connector FD = 35
```

**Comment by cassiodoroVicinetti** [comment]
Same issue here with version 0.9.3 on Debian testing

**Comment by eighthave** [comment]
maybe helpful? https://stackoverflow.com/a/32544210  seems there was a emulator bios bug that prevents boots on Linux 3.18+
