### ISSUE TITLE
Google Translate x86 native code?

### ISSUE THREAD

**Issue by orschiro** [shashlik/shashlik-build#21]
Dear all, 

Thank you so much for your work on Shashlik!

I found the project, installed the latest Ubuntu deb file and followed the [howtoforge](https://www.howtoforge.com/tutorial/how-to-install-and-run-android-apk-on-linux-with-shashlik/) tutorial with a Google Translate apk that I downloaded from https://apkpure.com.

However, it fails to install with the following message:

```
orschiro@x230:~/Downloads$ “/opt/shashlik/bin/shashlik-install Google\ Translate_v4.4.0.RC01.104701208_apkpure.com.apk 
bash: “/opt/shashlik/bin/shashlik-install: No such file or directory
orschiro@x230:~/Downloads$ /opt/shashlik/bin/shashlik-install Google\ Translate_v4.4.0.RC01.104701208_apkpure.com.apk 
This package does not contain x86 native code, and can't run. Please find another APK built for x86
Traceback (most recent call last):
  File "/opt/shashlik/bin/shashlik-install", line 63, in <module>
    message("This package does not contain x86 native code, and can't run. Please find another APK built for x86")
  File "/opt/shashlik/bin/shashlik-install", line 22, in message
    "--msgbox", msg])
  File "/usr/lib/python3.4/subprocess.py", line 537, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.4/subprocess.py", line 859, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.4/subprocess.py", line 1459, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'kdialog'
```

Is there any chance that I can get to run Google Translate or is it simply one of the applications that are currently not supported?

Thankfully,

~Robert

**Comment by licaon-kter** [comment]
Given that there is a `qemu-arm` I guess it's just another matter of available time/developers.

**Comment by orschiro** [comment]
Thank you @licaon-kter!

Does this mean that with future versions of Shashlik, Google Translate might
eventually be supported?

Warmly,

~Robert

Sent from [Nylas N1](https://nylas.com/n1?ref=n1), the extensible, open source
mail client.
