### ISSUE TITLE
image splash and no more

### ISSUE THREAD

**Issue by zzamyy** [shashlik/shashlik-build#26]
this is the log i capture after install and run 

https://gist.github.com/anonymous/0622c51a5e2ee0864ea9321b37486592

**Comment by ravsa** [comment]
I am getting the same image splash and nothing

**Comment by tuthan** [comment]
same here.  i have no idea what's wrong :(

**Comment by NyaomiDEV** [comment]
Same here.

Running 0.9.3 on Elementary OS 0.4 Loki (based on Ubuntu 16.04); Pentium Dual-Core E5300 2.6GHz; 4GB RAM

**Comment by frodo4fingers** [comment]
again, same here. i got the following output:

```bash
/opt/shashlik/bin/shashlik-run ak.alizandro.smartaudiobookplayer ak.alizandro.smartaudiobookplayer    
starting emulator
emulator: WARNING: system partition size adjusted to match image file (750 MB > 200 MB)

emulator: WARNING: data partition size adjusted to match image file (750 MB > 200 MB)

setting icon3 
setting icon1 
setting icon
Creating filesystem with parameters:
    Size: 69206016
    Block size: 4096
    Blocks per group: 32768
    Inodes per group: 4224
    Inode size: 256
    Journal blocks: 1024
    Label: 
    Blocks: 16896
    Block groups: 1
    Reserved block group size: 7
Created filesystem with 11/4224 inodes and 1302/16896 blocks
ParseResult(scheme='', netloc='', path='/apk_file', params='', query='', fragment='')
Sending APK
127.0.0.1 - - [26/Nov/2016 21:41:50] "GET /apk_file HTTP/1.1" 403 -
ParseResult(scheme='', netloc='', path='/startup', params='', query='', fragment='')
127.0.0.1 - - [26/Nov/2016 21:41:50] "GET /startup HTTP/1.1" 200 -
```

after that nothing happens... any idea?

**Comment by Granitosaurus** [comment]
Same here as well:

```
$ starting emulator
emulator: WARNING: system partition size adjusted to match image file (750 MB > 200 MB)

emulator: WARNING: data partition size adjusted to match image file (750 MB > 200 MB)

setting icon3 
setting icon1 
setting icon
Creating filesystem with parameters:
    Size: 69206016
    Block size: 4096
    Blocks per group: 32768
    Inodes per group: 4224
    Inode size: 256
    Journal blocks: 1024
    Label: 
    Blocks: 16896
    Block groups: 1
    Reserved block group size: 7
Created filesystem with 11/4224 inodes and 1302/16896 blocks
```

Tried a whole bunch of apps and all of them result in the same issue. Running on Arch with i3wm.

**Comment by cirrusUK** [comment]
did anyone figure this one out ? i too am running arch with dwm  (edited shashlik-run & shashlik-install to correct paths) i should let aur pkger know bout this, tho im sure he does already.

**Comment by elissongois** [comment]
elissongois@elissongois-PC:~$ /opt/shashlik/bin/shashlik-run splash RO_pro.1540798060.apk
starting emulator
emulator: WARNING: system partition size adjusted to match image file (750 MB > 200 MB)

emulator: ERROR: Invalid -datadir directory: /home/elissongois/.local/share/shashlik/system
emulator: WARNING: data partition size adjusted to match image file (750 MB > 200 MB)

setting icon3 
Creating filesystem with parameters:
    Size: 69206016
    Block size: 4096
    Blocks per group: 32768
    Inodes per group: 4224
    Inode size: 256
    Journal blocks: 1024
    Label: 
    Blocks: 16896
    Block groups: 1
    Reserved block group size: 7
Created filesystem with 11/4224 inodes and 1302/16896 blocks
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/shashlik/bin/shashlik-run", line 119, in send_icon
    with open(icon_path, "rb") as icon:
FileNotFoundError: [Errno 2] No such file or directory: '/home/elissongois/.local/share/shashlik/splash.png'
