### ISSUE TITLE
ERROR: dump failed because assets could not be loaded

### ISSUE THREAD

**Issue by nixoye** [shashlik/shashlik-build#30]
W/asset   (14576): Asset path GOLFMEDIA_com.whalerock.golfwang.apk is neither a directory nor file (type=1).
ERROR: dump failed because assets could not be loaded
Could not get APK info. Broken setup?
Traceback (most recent call last):
  File "/opt/shashlik/bin/shashlik-install", line 30, in <module>
    universal_newlines=True)
  File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/opt/shashlik/bin/aapt', 'dump', 'badging', 'GOLFMEDIA_com.whalerock.golfwang.apk']' returned non-zero exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/shashlik/bin/shashlik-install", line 32, in <module>
    message("Could not get APK info. Broken setup?")
  File "/opt/shashlik/bin/shashlik-install", line 22, in message
    "--msgbox", msg])
  File "/usr/lib/python3.5/subprocess.py", line 557, in call
    with Popen(_popenargs, *_kwargs) as p:
  File "/usr/lib/python3.5/subprocess.py", line 947, in **init**
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'kdialog'

i get this message when trying to install Golf Media with

> /opt/shashlik/bin/shashlik-install GOLFMEDIA_com.whalerock.golfwang.apk

running xubuntu 16.04
installed 0.9.3
would extremely appreciate being able to run this app on my computer since my phone cant handle streaming

**Comment by m3asmi** [comment]
That’s because kdialog is missing, and if you don’t like the error messages, it can be installed with:
`sudo apt-get install kde-baseapps-bin`
