### ISSUE TITLE
black screen 

### ISSUE THREAD

**Issue by sherifrad** [shashlik/shashlik-build#32]
i had installed the app (show box) . when i open the app there is only a black screen.
this is the ouput of the : `/opt/shashlik/bin/shashlik-run com.tdo.showbox.png showbox`
`emulator: WARNING: system partition size adjusted to match image file (750 MB > 200 MB)

emulator: ERROR: Invalid -datadir directory: /home/sherif/.local/share/shashlik/system
emulator: WARNING: data partition size adjusted to match image file (750 MB > 200 MB)

setting icon3 
Creating filesystem with parameters:
    Size: 786432000
    Block size: 4096
    Blocks per group: 32768
    Inodes per group: 8000
    Inode size: 256
    Journal blocks: 3000
    Label: 
    Blocks: 192000
    Block groups: 6
    Reserved block group size: 47
Created filesystem with 11/48000 inodes and 6211/192000 blocks
Creating filesystem with parameters:
    Size: 69206016
    Block size: 4096
    Blocks per group: 32768
    Inodes per group: 4224
    Inode size: 256
    Journal blocks: 1024
    Label: 
    Blocks: 16896
    Block groups: 1
    Reserved block group size: 7
Created filesystem with 11/4224 inodes and 1302/16896 blocks
Failed to load libGL.so
error libGL.so: cannot open shared object file: No such file or directory
Failed to load libGL.so
error libGL.so: cannot open shared object file: No such file or directory
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/shashlik/bin/shashlik-run", line 119, in send_icon
    with open(icon_path, "rb") as icon:
FileNotFoundError: [Errno 2] No such file or directory: '/home/sherif/.local/share/shashlik/com.tdo.showbox.png.png'
![screenshot from 2016-11-03 16-44-08](https://cloud.githubusercontent.com/assets/23216006/19970492/c93183e0-a1e4-11e6-8824-6fa70f1f1455.png)
`

**Comment by DoraemonYu** [comment]
In your environment, you need to type :
/opt/shashlik/bin/shashlik-run **com.tdo.showbox** showbox.

**Comment by gladstonedigital** [comment]
You should also install libgl.so. It depends what distro you're running: on Debian do this by `sudo apt install libgl1-mesa-dev`. The exact package and install command will vary depending on your distribution.

**Comment by panospetridisoglou** [comment]
try
`sudo apt-get install kde-baseapps-bin`
if you still have black screen switch to Intel Graphics or simply logout and re log in

**Comment by DoraemonYu** [comment]
@Panospetridisoglou  Thanks for your ideas.
In fact I have install the newest version of kde-baseapps-bin already.
I tried to restart and relogin system as well, but just still got a black screen.
However, I havn't another Graphics Card that is not Intel, so I cannot test this point this moment.
