### ISSUE TITLE
I can't install any apps

### ISSUE THREAD

**Issue by rubtec** [shashlik/shashlik-build#53]
I was try install some apps with /opt/shashlik/bin/shashlik-install, then that error occur:

/opt/shashlik/bin/shashlik-install  Arena_Game_v1.23.1.2_apkpure.com.apk
W/asset   ( 7541): Asset path Arena_Game_v1.23.1.2_apkpure.com.apk is neither a directory nor file (type=1).
ERROR: dump failed because assets could not be loaded
Could not get APK info. Broken setup?
Traceback (most recent call last):
  File "/opt/shashlik/bin/shashlik-install", line 30, in <module>
    universal_newlines=True)
  File "/home/rubens/anaconda3/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/home/rubens/anaconda3/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/opt/shashlik/bin/aapt', 'dump', 'badging', 'Arena_Game_v1.23.1.2_apkpure.com.apk']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/shashlik/bin/shashlik-install", line 32, in <module>
    message("Could not get APK info. Broken setup?")
  File "/opt/shashlik/bin/shashlik-install", line 22, in message
    "--msgbox", msg])
  File "/home/rubens/anaconda3/lib/python3.6/subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/home/rubens/anaconda3/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/home/rubens/anaconda3/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'kdialog': 'kdialog'

**Comment by gguerran** [comment]
solution: https://www.cnx-software.com/2016/03/08/run-android-apps-in-linux-with-shashlik-android-emulation-layer/
