### ISSUE TITLE
Debian Stretch

### ISSUE THREAD

**Issue by SoraKohaku** [shashlik/shashlik-build#56]
This package does not contain x86 native code, and can't run. Please find another APK built for x86
Traceback (most recent call last):
  File "/opt/shashlik/bin/shashlik-install", line 63, in <module>
    message("This package does not contain x86 native code, and can't run. Please find another APK built for x86")
  File "/opt/shashlik/bin/shashlik-install", line 22, in message
    "--msgbox", msg])
  File "/usr/lib/python3.5/subprocess.py", line 247, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.5/subprocess.py", line 676, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1282, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'kdialog'

**Comment by JeSTeRFLA** [comment]
same issue as above

also got a few other errors 
File "/opt/shashlik/bin/shashlik-install", line 109, in <module>
    message ("Successfully installed %s" % app_name)
  File "/opt/shashlik/bin/shashlik-install", line 22, in message
    "--msgbox", msg])
  File "/usr/lib/python3.7/subprocess.py", line 323, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
