### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by dammikapriyadarshani** [shashlik/shashlik-build#63]
/opt/shashlik/bin/shashlik-run imo.apk imo
starting emulator
emulator: WARNING: system partition size adjusted to match image file (750 MB > 200 MB)

emulator: ERROR: Invalid -datadir directory: /home/chathura/.local/share/shashlik/system
emulator: WARNING: data partition size adjusted to match image file (750 MB > 200 MB)

setting icon3 
WARNING: userdata image already in use, changes will not persist!
Creating filesystem with parameters:
    Size: 786432000
    Block size: 4096
    Blocks per group: 32768
    Inodes per group: 8000
    Inode size: 256
    Journal blocks: 3000
    Label: 
    Blocks: 192000
    Block groups: 6
    Reserved block group size: 47
Created filesystem with 11/48000 inodes and 6211/192000 blocks
Creating filesystem with parameters:
    Size: 69206016
    Block size: 4096
    Blocks per group: 32768
    Inodes per group: 4224
    Inode size: 256
    Journal blocks: 1024
    Label: 
    Blocks: 16896
    Block groups: 1
    Reserved block group size: 7
Created filesystem with 11/4224 inodes and 1302/16896 blocks
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/shashlik/bin/shashlik-run", line 119, in send_icon
    with open(icon_path, "rb") as icon:
FileNotFoundError: [Errno 2] No such file or directory: '/home/chathura/.local/share/shashlik/imo.apk.png'

That's my issue. Please help me

**Comment by dammikapriyadarshani** [comment]
Apk is not working

**Comment by reyhanboim** [comment]
me too
